name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install dependencies (CMake, g++)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      # Step 3: Configure the project using CMake
      - name: Configure project
        run: cmake -S . -B build

      # Step 4: Build the project
      - name: Build project
        run: cmake --build build --config Release
